// Generated by `pnpm db:types` once the migration is applied to a local
// Supabase instance. Re-run any time the schema changes.
//
// Until then we ship a hand-rolled minimum so the rest of the codebase can
// type-check. Replace this file's contents with the generated output.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Province =
  | 'AB' | 'BC' | 'MB' | 'NB' | 'NL' | 'NS' | 'NT' | 'NU'
  | 'ON' | 'PE' | 'QC' | 'SK' | 'YT';

export type LanguagePreference = 'en' | 'pa' | 'hi' | 'ur';
export type Currency = 'CAD' | 'USD';
export type LoadStatus = 'draft' | 'invoiced' | 'paid' | 'overdue';
export type InvoiceStatus = 'draft' | 'sent' | 'paid' | 'overdue';
export type SubscriptionPlan = 'solo' | 'plus';
export type SubscriptionStatus =
  | 'trialing' | 'active' | 'past_due' | 'canceled';

export interface Address {
  line1: string | null;
  line2: string | null;
  city: string | null;
  province: string | null;
  postal_code: string | null;
  country: string | null;
}

export interface Accessorial {
  description: string;
  amount: number;
}

interface ProfilesRow {
  id: string;
  company_name: string | null;
  gst_hst_number: string | null;
  mc_number: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  province: string | null;
  postal_code: string | null;
  country: string | null;
  phone: string | null;
  language_preference: LanguagePreference;
  onboarding_completed: boolean;
  created_at: string;
  updated_at: string;
}

interface BrokersRow {
  id: string;
  user_id: string;
  name: string;
  mc_number: string | null;
  ap_email: string | null;
  phone: string | null;
  payment_terms_days: number;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  province: string | null;
  postal_code: string | null;
  country: string | null;
  created_at: string;
}

interface LoadsRow {
  id: string;
  user_id: string;
  broker_id: string | null;
  load_number: string | null;
  pickup_date: string | null;
  pickup_address_line1: string | null;
  pickup_city: string | null;
  pickup_province: string | null;
  pickup_postal_code: string | null;
  pickup_country: string | null;
  delivery_date: string | null;
  delivery_address_line1: string | null;
  delivery_city: string | null;
  delivery_province: string | null;
  delivery_postal_code: string | null;
  delivery_country: string | null;
  distance_miles: number | null;
  equipment_type: string | null;
  line_haul_rate: number | null;
  fuel_surcharge: number | null;
  accessorials: Accessorial[];
  total_rate: number | null;
  payment_terms_days: number;
  currency: Currency;
  status: LoadStatus;
  rate_con_url: string | null;
  bol_url: string | null;
  pod_url: string | null;
  created_at: string;
  invoiced_at: string | null;
  paid_at: string | null;
}

interface InvoicesRow {
  id: string;
  user_id: string;
  load_id: string;
  invoice_number: string;
  issue_date: string;
  due_date: string;
  subtotal: number;
  gst_hst_rate: number;
  gst_hst_amount: number;
  total: number;
  currency: Currency;
  pdf_url: string | null;
  status: InvoiceStatus;
  sent_to_email: string | null;
  sent_at: string | null;
  paid_at: string | null;
  created_at: string;
}

interface SubscriptionsRow {
  id: string;
  user_id: string;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  plan: SubscriptionPlan | null;
  status: SubscriptionStatus | null;
  trial_end: string | null;
  current_period_end: string | null;
  created_at: string;
  updated_at: string;
}

interface StripeEventsRow {
  id: string;
  received_at: string;
}

export interface Database {
  // Sentinel that newer supabase-js / @supabase/ssr key off to exclude this
  // from schema-name resolution (`Exclude<keyof Database, '__InternalSupabase'>`).
  // Will be regenerated by `pnpm db:types` once migrations are applied.
  __InternalSupabase: { PostgrestVersion: '12' };
  public: {
    Tables: {
      profiles: {
        Row: ProfilesRow;
        Insert: Partial<ProfilesRow> & { id: string };
        Update: Partial<ProfilesRow>;
        Relationships: [];
      };
      brokers: {
        Row: BrokersRow;
        Insert: Omit<BrokersRow, 'id' | 'created_at'> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<BrokersRow>;
        Relationships: [];
      };
      loads: {
        Row: LoadsRow;
        Insert: Partial<LoadsRow> & { user_id: string };
        Update: Partial<LoadsRow>;
        Relationships: [];
      };
      invoices: {
        Row: InvoicesRow;
        Insert: Partial<InvoicesRow> & { user_id: string; load_id: string };
        Update: Partial<InvoicesRow>;
        Relationships: [];
      };
      subscriptions: {
        Row: SubscriptionsRow;
        Insert: Partial<SubscriptionsRow> & { user_id: string };
        Update: Partial<SubscriptionsRow>;
        Relationships: [];
      };
      stripe_events: {
        Row: StripeEventsRow;
        Insert: { id: string; received_at?: string };
        Update: Partial<StripeEventsRow>;
        Relationships: [];
      };
    };
    // supabase-js intersects Tables with Views; using Record<string, never>
    // here would collapse every column to `never`. Empty objects keep the
    // intersection no-op until real types are generated.
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
}
